version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4

    steps:
      - checkout

      - run: sudo composer self-update

      - restore_cache:
          keys:
            - composer-{{ checksum "composer.lock" }}

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - vendor
          key: composer-{{ checksum "composer.lock" }}

      - run:
          name: Lint
          command: vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix --dry-run --diff

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+.*$/
      #- publish:
      #    requires:
      #      - build
      #    filters:
      #      branches:
      #        ignore: /.*/
      #      tags:
      #        only: /^v\d+\.\d+\.\d+.*$/
