name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  id-token: write
  contents: write
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer
        uses: php-actions/composer@v6
        with:
          command: validate
          php_version: '8.3'

      - name: Cache dependencies
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-composer-sync-${{ hashFiles('**/composer.lock') }}-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        uses: php-actions/composer@v6
        with:
          php_version: '8.3'

      - name: Set default php version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Lint
        run: vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix --dry-run --diff

  push:

    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer
        uses: php-actions/composer@v6
        with:
          command: validate
          php_version: '8.3'

      - name: Clear dependencies
        run: rm -rf vendor

      - name: Cache dependencies
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-composer-no-dev-${{ hashFiles('**/composer.lock') }}-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        uses: php-actions/composer@v6
        with:
          php_version: '8.3'
      - name: Debug role variable
        run: echo "${{ vars.AWS_BLOCKCHYP_DEV_GITHUB_DEPLOY_ROLE }}"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::105741232974:role/GitHubDeployRoleWoocommerce
          aws-region: us-west-2
      - name: Sync to S3
        run: .github/deploy.sh s3
        env:
          TEST_S3_BUCKET: ${{ secrets.TEST_S3_BUCKET }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          WP_CLUSTER: ${{ secrets.WP_CLUSTER }}
          WP_SYNC_TASKDEF: ${{ secrets.WP_SYNC_TASKDEF }}
