name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Validate composer
        run: composer validate

      - name: Cache dependencies
        id: composer-cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-composer-deploy-no-dev-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest --no-dev

      - name: Install Subversion
        run: sudo apt-get update && sudo apt-get install -y subversion

      - name: Deploy
        run: .github/deploy.sh svn
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
